[Service]
Host = "edgex-device-random"
Port = 49988
ConnectRetries = 3
Labels = []
OpenMsg = "device random started"
ReadMaxLimit = 256
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "edgex-core-consul"
Port = 8500
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "edgex-core-data"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "edgex-core-metadata"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "edgex-support-logging"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "/edgex/logs/device-random.log"
Level = "INFO"

# Pre-define Devices
[[DeviceList]]
  Name = "Random-Integer-Generator01"
  Profile = "Random-Integer-Generator"
  Description = "Example of Device Random"
  Labels = [ "device-random-example" ]
  [DeviceList.Addressable]
    Address = "device-random-01"
    Protocol = "OTHER"

# Pre-define Schedule Configuration
[[Schedules]]
Name = "5sec-schedule"
Frequency = "PT5S"

[[ScheduleEvents]]
Name = "readValue_int8"
Schedule = "5sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/Random-Integer-Generator01/GenerateRandomValue_Int8"
[[ScheduleEvents]]
Name = "readValue_int16"
Schedule = "5sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/Random-Integer-Generator01/GenerateRandomValue_Int16"
[[ScheduleEvents]]
Name = "readValue_int32"
Schedule = "5sec-schedule"
  [ScheduleEvents.Addressable]
  HTTPMethod = "GET"
  Path = "/api/v1/device/name/Random-Integer-Generator01/GenerateRandomValue_Int32"
